-- ============================================================
-- Supabase Database Schema for Fine-Explain RAG Architecture
-- Execute this script in Supabase SQL Editor (SQL Editor -> New Query)
-- ============================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    product_type VARCHAR(100) NOT NULL,
    effective_date DATE,
    owner_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. DOCUMENTS TABLE
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    file_hash VARCHAR(64) UNIQUE NOT NULL,
    s3_key VARCHAR(512),
    file_size INTEGER NOT NULL,
    total_pages INTEGER DEFAULT 0,
    status VARCHAR(50) DEFAULT 'uploaded',
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CHUNKS TABLE (Metadata store alongside Pinecone vector index)
CREATE TABLE IF NOT EXISTS public.chunks (
    id VARCHAR(128) PRIMARY KEY, -- Document-Chunk UUID or Pinecone Vector ID
    document_id BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
    parent_id VARCHAR(128),
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    page_number INTEGER,
    section_title VARCHAR(255),
    token_count INTEGER,
    tsv tsvector GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for BM25 / PostgreSQL Full-Text Search
CREATE INDEX IF NOT EXISTS idx_chunks_tsv ON public.chunks USING GIN (tsv);
CREATE INDEX IF NOT EXISTS idx_chunks_document_id ON public.chunks(document_id);

-- 5. HILT TASKS TABLE (Human-in-the-Loop)
CREATE TABLE IF NOT EXISTS public.hilt_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    task_type VARCHAR(50) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    resolution_data JSONB,
    resolver_user_id BIGINT REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

-- 6. VERIFIED ANSWERS TABLE (Feedback Loop & Evaluation)
CREATE TABLE IF NOT EXISTS public.verified_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_query TEXT NOT NULL,
    context_hash VARCHAR(64),
    final_answer TEXT NOT NULL,
    source_citations JSONB DEFAULT '[]'::jsonb,
    confidence_score FLOAT,
    verified_by_user_id BIGINT REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. SCENARIOS TABLE
CREATE TABLE IF NOT EXISTS public.scenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    principal NUMERIC(15, 2) NOT NULL,
    duration_months INTEGER NOT NULL,
    interest_rate NUMERIC(5, 2),
    parameters JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
